### PR TITLE
WIP Markers

### PR DESCRIPTION
**Pull request by bmatherly**
Instructions:

* Press <kbd>M</kbd> to create a marker on the timeline at the current playhead position
* Click and drag to move markers
* <kbd>Ctrl</kbd>+click and drag to change the range of a marker (default is 1 frame)
* Right-click a marker to edit

TODO:

- [ ] Display marker information in the bubble status (in progress)
- [x] Click to seek to it
- [x] Edit keyboard shortcut (<kbd>M</kbd>)
- [x] Toolbar button
- [x] Delete keyboard shortcut (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>M</kbd>)
- [x] Export marker range

Out-of-scope but desired:

* Snap or skip to markers
* Create chapters from markers
* Ripple with timeline operations
* Display all markers in a **Markers** panel

Comments welcome on size, location, usability. I personally wonder if the marker handles are too small. Maybe the ruler height should be increased to allow the markers to be bigger.

### CODE REVIEW

**Comment by ddennedy** [comment]
I edited the description to prioritize the TODO list against the design doc. I will not include the out-of-scope items in the first release but "Create (YouTube) chapters" should be fairly easy using the JavaScript-based framework I made for exporting EDL.

**Comment by bmatherly** [comment]
> I edited the description to prioritize the TODO list against the design doc.

Thanks.

One problem I have not solved for the keyboard shortcut is that currently I do not have a concept of a "selected" marker. I could infer a selected marker by looking at what marker is under the playhead - and ignoring a command if there is no marker under a playhead. However, I also do not currently prohibit overlapping markers.

For keyboard shortcuts, I propose to apply the keyboard shortcut command to the first marker that aligns with the playhead. Thoughts?

In addition to YouTube chapters, there was also a request to create file chapters for containers that support chapters. FFMpeg has an interface to specify chapters - and I think we could map markers over to the FFMpeg chapter metadata to support that eventually.

**Comment by ddennedy** [comment]
I will start working on the toolbar button.

**Comment by ddennedy** [comment]
Regarding the selected marker for edit and redundant markers. At first I was thinking that you would be prohibited from creating redundant markers because the marker command would automatically choose new or edit depending on if it exists. However, edit and dragging still lets you have more than one marker with the same start time. I think initially we should just make the command edit the first marker if finds. Later, we can add a popup menu listing them for choice.

**Comment by bmatherly** [comment]
>I think initially we should just make the command edit the first marker if finds. Later, we can add a popup menu listing them for choice.

Agreed. I think overlapping will be uncommon.

**Comment by ddennedy** [comment]
See #1167 where I fixed and added a number of things including export! I am willing to merge this as-is for a beta. You can try to add the bubble help by end of Oct. 17, but it can also be added during beta IMO. However, I would like you to review more of my changes on the origin branch before I merge by EOD Oct. 17.

**Pull request closed without merging**
