### PR TITLE
Add tootip to timeline clips

### PR DESCRIPTION
**Pull request by bmatherly**
Show clip name, comment and duration

As suggested here:
https://forum.shotcut.org/t/show-clips-comments-in-the-timeline/32131/3

This uses the standard tooltip which has a delayed popup after hover

image

### CODE REVIEW

**Review by ddennedy — CHANGES_REQUESTED** [review]
There are a few problems with it:
1. It shows up for "blank"s
2. When I edit the comments in properties, the tooltip is not updated.
3. A long comment makes a very big tooltip and it should probably be elided while considering not only line length but number of lines.
3. It shows when dragging a clip along with the time "bubble help", which is distracting as they are in different places and look different.

Consider adding an option in the timeline menu, options sub-menu that defaults to on.

**Comment by bmatherly** [comment]
> It shows up for "blank"s

fixed

> When I edit the comments in properties, the tooltip is not updated.

fixed

> A long comment makes a very big tooltip and it should probably be elided while considering not only line length but number of lines.

I am not sure what to do about this. The ToolTip control does not support elided text. I am thinking about writing a javascript function to manually truncate/elide lines that are longer than 50 characters and to limit the comment to 3 lines.

Thoughts?

> It shows when dragging a clip along with the time "bubble help", which is distracting as they are in different places and look different.

fixed

> Consider adding an option in the timeline menu, options sub-menu that defaults to on.

I am not sure if this is worthy of a menu option. Do you think that some users will not like this feature? If so, maybe we should just reject the idea. I do not feel strongly about the idea. It just seems like an easy thing to change.

**Comment by ddennedy** [comment]
I think the eliding function idea is good. We can leave the menu option out for now and add it later if it seems desirable.

**Comment by bmatherly** [comment]
I think this was closed by accident?

**Comment by ddennedy** [comment]
Yes an accident

**Comment by bmatherly** [comment]
I added a manual "elide" to the comment to limit the size.

image

**Review by ddennedy — APPROVED** [review]

**Pull request merged**
