### PR TITLE
Webvfx in out point fix

### LINKED ISSUE #77: Non-fadein/out filter in/out points are not updated
Trying to use the time argument in webvfx I noticed that the in/out points were not updated when the clip was resized. I eventually tracked it down to MultitrackModel::trimClipIn (among others)
```
        // Adjust all filters that have an explicit duration.
        int n = info->producer->filter_count();
        for (int j = 0; j < n; j++) {
            Mlt::Filter* filter = info->producer->filter(j);
            if (filter && filter->is_valid() && filter->get_length() > 0) {
                if (QString(filter->get(kShotcutFilterProperty)).startsWith("fadeIn"))
                    filter->set_in_and_out(in, in + filter->get_length() - 1);
            }
            delete filter;
        }
```
This startsWith test was added in 1456ff84
So in webvfx's case, the filter in/out is only set once, in Component.onCompleted in the filter ui, and never again.

I have not yet had time to look at possible solutions, but my initial impression is that QString(filter->get(kShotcutFilterProperty)).startsWith("fadeIn") looks hackish.

### PR DESCRIPTION
**Pull request by metellius**
Fixes #77

### CODE REVIEW

**Comment by ddennedy** [comment]
Check the property mlt_service=webvfx as I asked previously. Do not add objectName to overlay HTML filter as that is the fallback for any webvfx-based filter that does qualify itself with a "shotcut:filter"

**Comment by metellius** [comment]
Closed? Should I post a new pull request for the correct fixes?

**Comment by ddennedy** [comment]
sorry, re-opened

**Comment by metellius** [comment]
Is there anything missing for this to get merged?

**Pull request merged**
