### PR TITLE
Add support for MLT links as Filters

### PR DESCRIPTION
**Pull request by bmatherly**
Depends on https://github.com/mltframework/mlt/pull/615

### CODE REVIEW

**Comment by ddennedy** [comment]
I added a branch named "MLTv7" onto which you can rebase this and resolve conflicts.

**Comment by bmatherly** [comment]
This should be good now.

Also, I wonder if some of these filterview changes need to be in master https://github.com/mltframework/shotcut/pull/936/commits/14b4becdbf2ac10a205a188341520e7538aeade6
The "remove filter" button was not working for me in Qt 5.12 in this branch until I made these changes in filterview.

**Comment by ddennedy** [comment]
I just tested remove filter on the 21.01 releases for Windows and macOS, and it is working for me. So, I want to hold off merging that into master.

**Comment by ddennedy** [comment]
I am running into this problem now with remove filter button due to a regression in 1b668b05.

**Pull request merged**
