### PR TITLE
Fix keyframes are lost when trimming transition

### PR DESCRIPTION
**Pull request by bmatherly**
As reported here:
https://forum.shotcut.org/t/pulling-on-the-left-side-of-a-transition-clip-can-mess-up-and-erase-all-keyframes/35837

Also improve updating the keyframes panel if it is affected by transition trimming

### CODE REVIEW

**Comment by ddennedy** [comment]
This is doing something wrong with adjusting the filter in and out points. You do not need to use keyframes to see this. Just add a filter (untrimmed) to each clip involved in the transition, trim the transition a little back and forth, and the filter on each may be trimmed unexpectedly as a result:
image

image

**Comment by bmatherly** [comment]
> trim the transition a little back and forth, and the filter on each may be trimmed unexpectedly as a result:

That was existing behavior, so I thought that was expected. I can look at it more later. When the transition "in" is trimmed, I can not figure out why the 2nd clip would be changed at all. I think the expectation is that trimming the left (in) side of a transition should have no affect on the clip on the right. Is that correct?

**Comment by ddennedy** [comment]
> That was existing behavior

not what I saw when comparing with release. It only does that when the filter in or out is not the same as the clip’s in and out. When they are the same trimming needs to adjust filters to match.

> When the transition "in" is trimmed, I can not figure out why the 2nd clip would be changed at all.

very simple. the second clip needs to be extended to cover the new transition or to contract.

**Comment by bmatherly** [comment]
> very simple. the second clip needs to be extended to cover the new transition or to contract.

Ok. I understand, but I am not finding a solution. Can you take a look at this one?

**Pull request closed without merging**
