### PR TITLE
WIP: add cmake build system

### PR DESCRIPTION
**Pull request by eszlari**
only tested on Linux, no install target, build works from the tree

### CODE REVIEW

**Comment by ddennedy** [comment]
Why?

**Comment by eszlari** [comment]
> Why?

* dependency discovery
* same build system for both mlt & shotcut
* faster (https://ninja-build.org)
* better IDE/editor support
* can generate `compile_commands.json` (https://clangd.llvm.org)
* pre-compiled headers

**Comment by ddennedy** [comment]
Thanks, and I agree these are nice to have, but I have a ton to deal with. I do not want to personally deal with a new build system in the near term. Qt 6 will be the main driver, but there is a lot of work to even get close to trying it. In order to merge this, it will need:
- updated build scripts
- work on all supported OS
- When I open the project in Qt Creator I also want to be able to see the OTHER_FILES in the Projects tree.

**Comment by eszlari** [comment]
>     * work on all supported OS

Linux & Windows: OK
macOS: I don't have any Apple devices.

**Comment by eszlari** [comment]
btw: What would be the TODO list to switch MLT to completely to cmake (remove the old gmake system)?

**Comment by brunetton** [comment]
Hi @eszlari sorry to ask but: how to compile using cmake ? (after cloning your fork repo and checkouting `cmake` branch, of course). Thanks

**Comment by brunetton** [comment]
🎉🎉🎉

**Pull request merged**
