### PR TITLE
Image File Compression

### PR DESCRIPTION
**Pull request by Peppernrino**
Ran a series of lossless compression algorithms to make the images smaller. Total reduction of 84,673 bytes.

Example here: https://pastebin.com/MTtcVck2

### CODE REVIEW

**Comment by ddennedy** [comment]
I am not very interested this because the saving is insignificant, and I maintain these from other sources where icons are added over time. I would be interested in a pull request that integrates with the build system or github.

**Comment by Peppernrino** [comment]
Ok. :)

**Comment by ddennedy** [comment]
I need a process that can be repeated, and I do not want it to to depend on a crapload of utilities.  Pick one or two and integrate it as a make target in either src/src.pro or new scripts/Makefile. Then, I can periodically run make to repeat the process when icons are changed or added. Thanks

**Comment by ddennedy** [comment]
Superseded by #706

**Pull request closed without merging**
