### PR TITLE
Simplified Chinese translated.

### PR DESCRIPTION
**Pull request by Kongse**
The translation is done by using the current Simplified Chinese untranslated ts file as framework, and the Traditional Chinese translation file as the phasebook. Lots of words have been modified to fit in Simplified Chinese style. Tranlations have been checked on application.

### CODE REVIEW

**Comment by ddennedy** [comment]
You must use transifex.com for this. I do not accept translation updates any other way at the moment because I would have to figure out a workflow that works with other translators using that service.

**Comment by Kongse** [comment]
I've not known that there is a translation colabration site. It's a nice workflow, ok I will finish the zh_CN translation on it.

**Comment by Kongse** [comment]
Remaining zh_CN tranlations on transifex finished.

**Comment by ddennedy** [comment]
Thank you. It is nice to get this translation updated.

**Comment by Kongse** [comment]
You guys made a great video editing software, very handy, thank you too.

**Pull request closed without merging**
