### PR TITLE
Keyboard shortcut improvements

### PR DESCRIPTION
**Pull request by metellius**
This branch has many improvements centered around keyboard control in shotcut.

- selecting multiple clips is now possible, due to selection being stored in an index array (ie [0,2,3])
   - this functionality is not yet exposed in the UI
- global keyboard shortcut code is moved to MainWindow
- the playlist eating some keypresses is fixed
- the current selection can now be moved with Shift+Arrow keys
     - As a part of this, empty spaces can now also be selected, so that they may be removed with X without reaching for the mouse. This might be the most risky change, and I know of at least one unfixed bug so far (the blank clip may be opened by pressing Enter, and then appending that clip does weird stuff)
- clips may be removed using X without selecting them first
- pressing Esc clears selection

### CODE REVIEW

**Comment by metellius** [comment]
To be honest, I didn't spend too much time actually using these new mechanisms until submitting this pull request - I'm sure there are still tweaking to be done on the behavior. For example I'm wondering if the playhead and the selection is conflicting a bit with these changes.

**Comment by ddennedy** [comment]
I am going on holiday for a week starting tomorrow and unable to test this until I return. In the meantime, please make sure your changes work correctly with undo and redo. Otherwise, I do not object to anything from the description provided.

**Comment by metellius** [comment]
Thanks, good to know. I'm back to work again the day after tomorrow, and I already know about bugs that need fixing, so there's no rush.

**Comment by metellius** [comment]
For the sake of reviewability, I chose to keep things in many smaller commits, and as such I recommend viewing the branch in git log -p or similar (I can't seem to find an equivalant in github, and viewing the pull request all squashed together makes it appear as the result of a very long unstructured nighttime hacking session )

**Comment by ddennedy** [comment]
Do not be discourage by my comments. There are many nice things in here. Also, please add a comment header to the top of new files. Thanks

**Comment by metellius** [comment]
> please add a comment header to the top of new files

What should it say? Something like this?

```
/*
 * Copyright (c) 2013-2014 Meltytech, LLC
 * Author: Harald Hvaal <harald.hvaal@gmail.com>
 *
...
```

**Comment by ddennedy** [comment]
Regarding the comment header, yes, but use "2015" instead of "2013-2014" for the date since the file was added in 2015. When I modify a file, I try to remember to bump up the year if needed. I do not make a pass across the entire code base on new years day. Usually, I am trying to enjoy my holiday. :-)

**Comment by ddennedy** [comment]
Another regression is that shift plus mouse-x over timeline no longer skims (scrubs) the player.

**Comment by metellius** [comment]
All the regressions should be addressed now.

**Comment by ddennedy** [comment]
Something is eating clicks on the blank areas of the timeline and timeline ruler and as result not seeking as expected. Drags work, but not single-clicks.

**Comment by ddennedy** [comment]
About currentTrack, currentClipTrack, and resetting selection upon changing current track; I initially reacted to the change in behavior. Now, I am wondering if there is much value in keeping that behavior. I guess it's not that important and we just need to take care of the actions in TimelineToolbar.qml to use currentTrack and selection to prevent triggering asserts.

**Comment by ddennedy** [comment]
I accepted the behavior change with respect to and clip selection and current track, fixed the toolbar action errors, fixed click-to-seek, and merged.

**Comment by metellius** [comment]
I'm not surprised I broke the behavior because I didn't even notice it was like that originally until you explained it now.

There is still refactoring to be done on the way selections are done, but I think the first round of commits here make it less of a challenging task. Specifically selecting multiple clips should be possible, and in order to do this each selected item in the current-selection array also needs to be coupled with which track it's on. I guess it would be easier if there was an unique persistent ID (I get that pointers to producers are not suitable for this) for the clips instead of the clipIndex+trackIndex combination that is so prevalent in the function signatures.

It sounds like going down that route will again make your comments here relevant due to current track and current selection being disconnected again. Do you think it's a bad idea?

**Pull request merged**
