### PR TITLE
Rippled trimming

### PR DESCRIPTION
**Pull request by metellius**
Main feature is rippled trimming, but I have also included some other smaller improvements that I have been accumulating.

### CODE REVIEW

**Comment by ddennedy** [comment]
I merged 3 of these commits tonight.

**Comment by ddennedy** [comment]
Do you think you can rebase this onto master and submit a new pull request for that?
Also, I am reviewing the modifiers for new shortcuts. Take an overview look at all them today:
http://www.shotcut.org/bin/view/Shotcut/KeyboardShortcuts

I have been using Shift variants of some to target the playlist and Timeline tends to use Ctrl. Perhaps regardless of this pull request, Playlist Ctrl+Up/Down should be changed to Shift. Perhaps your new Shift+I/O/U changed to Ctrl. Hmm, no, that will not work. :-) Ctrl+O and Ctrl+U are already taken. Playlist uses Shift+B for update. Perhaps Alt+B can be used for Timeline. It is, after all, a variant of Overwrite. In that case, Alt+I/O for timeline trimming? However, I am not highly opposed to Shift for them - just thinking. At some point, we will want shortcuts to seek in/out in the Source player. Final Cut and Premiere uses Shift for that, while Avid uses Alt. We do tends towards Avid on shortcuts.

**Comment by ddennedy** [comment]
Never mind about the shortcuts. I decided to leave them as you have it.

**Comment by metellius** [comment]
About to push a rebase. I'm leaving out a few commits that are not ready, but the rest should be ready for review.

**Comment by ddennedy** [comment]
Shift+U needs to request audio levels update.

**Comment by metellius** [comment]
that's one of the ones that is not ready, there are bugs, i'm not what keyboard shortcut to use, and i'm not sure how it fits in with rippling.

**Comment by metellius** [comment]
FYI, I've used this branch for a while without experiencing crashes.

**Comment by ddennedy** [comment]
Can you please add a checkmark icon - same one as used in PlaylistDock - to the timeline toolbar to trigger the update action? Put it between Overwrite and Split. And add a corresponding context menu action to Clip to trigger it as well. These should be disabled when the action is not applicable.

**Comment by metellius** [comment]
The update action isn't a part of this pr because i haven't spent much time
trying it out, but if you feel it should be i guess i can do that.

**Comment by ddennedy** [comment]
On Sun, Oct 18, 2015 at 1:58 PM metellius <notifications@github.com> wrote:

> The update action isn't a part of this pr because i haven't spent much time
> trying it out, but if you feel it should be i guess i can do that.
>

Oops. No, this is all we should include for this pull request. If you want
to continue to work on update in a separate branch and submit it, then feel
free.

**Comment by metellius** [comment]
I'm guessing you didn't intend to merge this into the qt5.5 branch... it was originally based on that branch.

**Pull request merged**
